#AUTOGENERATED! DO NOT EDIT! File to edit: dev/00_core.ipynb (unless otherwise specified).

__all__ = ['Toto']

#Cell
class Toto():
    def __init__(self,a):
        self.a=a
    def x():
        return 1
